spring:
  datasource:
    url: jdbc:mysql://localhost:3306/inscricao
    username: root
    password:
    driverClassName: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
management:
  endpoints:
    web:
      exposure:
        include: "health"
  endpoint:
    health:
      show-details: NEVER